controller_frequency: 4

TrajectoryPlannerROS:
  max_vel_x: 0.5 #0.5
  min_vel_x: 0.1 #0.01
  max_vel_theta: 0.57 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  sim_time: 1.0

  vx_samples: 3.0
  vy_samples: 3.0
  vtheta_samples: 20.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.001

  holonomic_robot: false
